module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      fontFamily: {
        sans: ["Roboto", "sans-serif"],
        contentFont: ["Oxygen", "sans-serif"],
        boldTallFont: ["Oswald", "sans-serif"],
        thinFont: ["BioRhyme", "serif"],
        thinKidFont: ["Nunito", "sans-serif"],
        fatKidFont: ["Concert One", "cursive"],
        medievalFont: ["Cormorant Upright", "serif"],
        shortHulkFont: ["Rubik Mono One", "sans-serif"],
      },
      screens: {
        sm: { max: "400px" },
        md: { min: "401px", max: "720px" },
        lg: { min: "721px" },
      },
      colors: {
        transparent: "transparent",
        black: "#000",
        white: "#fff",
        ferrariRed: "#EA2300",
        gamboge: "#EF9B0C",
        halloweenOrange: "#EA5F21",
        lightSilver: "#D3DCDE",
        blueSapphire: "#065774",
        prussianBlue: "#042B58",
      },
      spacing: {
        px: "1px",
        0: "0",
        0.5: "0.125rem",
        1: "0.25rem",
        1.5: "0.375rem",
        2: "0.5rem",
        2.5: "0.625rem",
        3: "0.75rem",
        3.5: "0.875rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        7: "1.75rem",
        8: "2rem",
        9: "2.25rem",
        10: "2.5rem",
        11: "2.75rem",
        12: "3rem",
        14: "3.5rem",
        16: "4rem",
        20: "5rem",
        24: "6rem",
        28: "7rem",
        32: "8rem",
        36: "9rem",
        40: "10rem",
      },
      borderRadius: {
        none: "0",
        sm: ".125rem",
        DEFAULT: ".25rem",
        lg: ".5rem",
        full: "9999px",
      },
      opacity: {
        0: "0",
        20: "0.2",
        40: "0.4",
        60: "0.6",
        80: "0.8",
        100: "1",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
